// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/avc/loyalty-system-diploma/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// AccrualClientMock is an autogenerated mock type for the AccrualClient type
type AccrualClientMock struct {
	mock.Mock
}

type AccrualClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AccrualClientMock) EXPECT() *AccrualClientMock_Expecter {
	return &AccrualClientMock_Expecter{mock: &_m.Mock}
}

// GetOrderAccrual provides a mock function with given fields: ctx, orderNumber
func (_m *AccrualClientMock) GetOrderAccrual(ctx context.Context, orderNumber string) (*domain.AccrualResponse, error) {
	ret := _m.Called(ctx, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderAccrual")
	}

	var r0 *domain.AccrualResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.AccrualResponse, error)); ok {
		return rf(ctx, orderNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.AccrualResponse); ok {
		r0 = rf(ctx, orderNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AccrualResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccrualClientMock_GetOrderAccrual_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderAccrual'
type AccrualClientMock_GetOrderAccrual_Call struct {
	*mock.Call
}

// GetOrderAccrual is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNumber string
func (_e *AccrualClientMock_Expecter) GetOrderAccrual(ctx interface{}, orderNumber interface{}) *AccrualClientMock_GetOrderAccrual_Call {
	return &AccrualClientMock_GetOrderAccrual_Call{Call: _e.mock.On("GetOrderAccrual", ctx, orderNumber)}
}

func (_c *AccrualClientMock_GetOrderAccrual_Call) Run(run func(ctx context.Context, orderNumber string)) *AccrualClientMock_GetOrderAccrual_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AccrualClientMock_GetOrderAccrual_Call) Return(_a0 *domain.AccrualResponse, _a1 error) *AccrualClientMock_GetOrderAccrual_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccrualClientMock_GetOrderAccrual_Call) RunAndReturn(run func(context.Context, string) (*domain.AccrualResponse, error)) *AccrualClientMock_GetOrderAccrual_Call {
	_c.Call.Return(run)
	return _c
}

// NewAccrualClientMock creates a new instance of AccrualClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccrualClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccrualClientMock {
	mock := &AccrualClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
