// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/avc/loyalty-system-diploma/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// BalanceServiceMock is an autogenerated mock type for the BalanceService type
type BalanceServiceMock struct {
	mock.Mock
}

type BalanceServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *BalanceServiceMock) EXPECT() *BalanceServiceMock_Expecter {
	return &BalanceServiceMock_Expecter{mock: &_m.Mock}
}

// GetBalance provides a mock function with given fields: ctx, userID
func (_m *BalanceServiceMock) GetBalance(ctx context.Context, userID int64) (*domain.Balance, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *domain.Balance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.Balance, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Balance); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Balance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BalanceServiceMock_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type BalanceServiceMock_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *BalanceServiceMock_Expecter) GetBalance(ctx interface{}, userID interface{}) *BalanceServiceMock_GetBalance_Call {
	return &BalanceServiceMock_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, userID)}
}

func (_c *BalanceServiceMock_GetBalance_Call) Run(run func(ctx context.Context, userID int64)) *BalanceServiceMock_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *BalanceServiceMock_GetBalance_Call) Return(_a0 *domain.Balance, _a1 error) *BalanceServiceMock_GetBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BalanceServiceMock_GetBalance_Call) RunAndReturn(run func(context.Context, int64) (*domain.Balance, error)) *BalanceServiceMock_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithdrawals provides a mock function with given fields: ctx, userID
func (_m *BalanceServiceMock) GetWithdrawals(ctx context.Context, userID int64) ([]*domain.Transaction, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawals")
	}

	var r0 []*domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*domain.Transaction, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*domain.Transaction); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BalanceServiceMock_GetWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithdrawals'
type BalanceServiceMock_GetWithdrawals_Call struct {
	*mock.Call
}

// GetWithdrawals is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *BalanceServiceMock_Expecter) GetWithdrawals(ctx interface{}, userID interface{}) *BalanceServiceMock_GetWithdrawals_Call {
	return &BalanceServiceMock_GetWithdrawals_Call{Call: _e.mock.On("GetWithdrawals", ctx, userID)}
}

func (_c *BalanceServiceMock_GetWithdrawals_Call) Run(run func(ctx context.Context, userID int64)) *BalanceServiceMock_GetWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *BalanceServiceMock_GetWithdrawals_Call) Return(_a0 []*domain.Transaction, _a1 error) *BalanceServiceMock_GetWithdrawals_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BalanceServiceMock_GetWithdrawals_Call) RunAndReturn(run func(context.Context, int64) ([]*domain.Transaction, error)) *BalanceServiceMock_GetWithdrawals_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function with given fields: ctx, userID, orderNumber, amount
func (_m *BalanceServiceMock) Withdraw(ctx context.Context, userID int64, orderNumber string, amount float64) error {
	ret := _m.Called(ctx, userID, orderNumber, amount)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, float64) error); ok {
		r0 = rf(ctx, userID, orderNumber, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BalanceServiceMock_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type BalanceServiceMock_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - orderNumber string
//   - amount float64
func (_e *BalanceServiceMock_Expecter) Withdraw(ctx interface{}, userID interface{}, orderNumber interface{}, amount interface{}) *BalanceServiceMock_Withdraw_Call {
	return &BalanceServiceMock_Withdraw_Call{Call: _e.mock.On("Withdraw", ctx, userID, orderNumber, amount)}
}

func (_c *BalanceServiceMock_Withdraw_Call) Run(run func(ctx context.Context, userID int64, orderNumber string, amount float64)) *BalanceServiceMock_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(float64))
	})
	return _c
}

func (_c *BalanceServiceMock_Withdraw_Call) Return(_a0 error) *BalanceServiceMock_Withdraw_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BalanceServiceMock_Withdraw_Call) RunAndReturn(run func(context.Context, int64, string, float64) error) *BalanceServiceMock_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}

// NewBalanceServiceMock creates a new instance of BalanceServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBalanceServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *BalanceServiceMock {
	mock := &BalanceServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
