// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/avc/loyalty-system-diploma/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// OrderServiceMock is an autogenerated mock type for the OrderService type
type OrderServiceMock struct {
	mock.Mock
}

type OrderServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderServiceMock) EXPECT() *OrderServiceMock_Expecter {
	return &OrderServiceMock_Expecter{mock: &_m.Mock}
}

// GetOrders provides a mock function with given fields: ctx, userID
func (_m *OrderServiceMock) GetOrders(ctx context.Context, userID int64) ([]*domain.Order, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrders")
	}

	var r0 []*domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*domain.Order, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*domain.Order); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderServiceMock_GetOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrders'
type OrderServiceMock_GetOrders_Call struct {
	*mock.Call
}

// GetOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *OrderServiceMock_Expecter) GetOrders(ctx interface{}, userID interface{}) *OrderServiceMock_GetOrders_Call {
	return &OrderServiceMock_GetOrders_Call{Call: _e.mock.On("GetOrders", ctx, userID)}
}

func (_c *OrderServiceMock_GetOrders_Call) Run(run func(ctx context.Context, userID int64)) *OrderServiceMock_GetOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *OrderServiceMock_GetOrders_Call) Return(_a0 []*domain.Order, _a1 error) *OrderServiceMock_GetOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderServiceMock_GetOrders_Call) RunAndReturn(run func(context.Context, int64) ([]*domain.Order, error)) *OrderServiceMock_GetOrders_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitOrder provides a mock function with given fields: ctx, userID, orderNumber
func (_m *OrderServiceMock) SubmitOrder(ctx context.Context, userID int64, orderNumber string) error {
	ret := _m.Called(ctx, userID, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for SubmitOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, userID, orderNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderServiceMock_SubmitOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitOrder'
type OrderServiceMock_SubmitOrder_Call struct {
	*mock.Call
}

// SubmitOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - orderNumber string
func (_e *OrderServiceMock_Expecter) SubmitOrder(ctx interface{}, userID interface{}, orderNumber interface{}) *OrderServiceMock_SubmitOrder_Call {
	return &OrderServiceMock_SubmitOrder_Call{Call: _e.mock.On("SubmitOrder", ctx, userID, orderNumber)}
}

func (_c *OrderServiceMock_SubmitOrder_Call) Run(run func(ctx context.Context, userID int64, orderNumber string)) *OrderServiceMock_SubmitOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *OrderServiceMock_SubmitOrder_Call) Return(_a0 error) *OrderServiceMock_SubmitOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderServiceMock_SubmitOrder_Call) RunAndReturn(run func(context.Context, int64, string) error) *OrderServiceMock_SubmitOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderServiceMock creates a new instance of OrderServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderServiceMock {
	mock := &OrderServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
