// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/avc/loyalty-system-diploma/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// OrderRepositoryMock is an autogenerated mock type for the OrderRepository type
type OrderRepositoryMock struct {
	mock.Mock
}

type OrderRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepositoryMock) EXPECT() *OrderRepositoryMock_Expecter {
	return &OrderRepositoryMock_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function with given fields: ctx, userID, number
func (_m *OrderRepositoryMock) CreateOrder(ctx context.Context, userID int64, number string) (*domain.Order, error) {
	ret := _m.Called(ctx, userID, number)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (*domain.Order, error)); ok {
		return rf(ctx, userID, number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) *domain.Order); ok {
		r0 = rf(ctx, userID, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, userID, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepositoryMock_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderRepositoryMock_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - number string
func (_e *OrderRepositoryMock_Expecter) CreateOrder(ctx interface{}, userID interface{}, number interface{}) *OrderRepositoryMock_CreateOrder_Call {
	return &OrderRepositoryMock_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, userID, number)}
}

func (_c *OrderRepositoryMock_CreateOrder_Call) Run(run func(ctx context.Context, userID int64, number string)) *OrderRepositoryMock_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *OrderRepositoryMock_CreateOrder_Call) Return(_a0 *domain.Order, _a1 error) *OrderRepositoryMock_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepositoryMock_CreateOrder_Call) RunAndReturn(run func(context.Context, int64, string) (*domain.Order, error)) *OrderRepositoryMock_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderByNumber provides a mock function with given fields: ctx, number
func (_m *OrderRepositoryMock) GetOrderByNumber(ctx context.Context, number string) (*domain.Order, error) {
	ret := _m.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByNumber")
	}

	var r0 *domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Order, error)); ok {
		return rf(ctx, number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Order); ok {
		r0 = rf(ctx, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepositoryMock_GetOrderByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByNumber'
type OrderRepositoryMock_GetOrderByNumber_Call struct {
	*mock.Call
}

// GetOrderByNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - number string
func (_e *OrderRepositoryMock_Expecter) GetOrderByNumber(ctx interface{}, number interface{}) *OrderRepositoryMock_GetOrderByNumber_Call {
	return &OrderRepositoryMock_GetOrderByNumber_Call{Call: _e.mock.On("GetOrderByNumber", ctx, number)}
}

func (_c *OrderRepositoryMock_GetOrderByNumber_Call) Run(run func(ctx context.Context, number string)) *OrderRepositoryMock_GetOrderByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderRepositoryMock_GetOrderByNumber_Call) Return(_a0 *domain.Order, _a1 error) *OrderRepositoryMock_GetOrderByNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepositoryMock_GetOrderByNumber_Call) RunAndReturn(run func(context.Context, string) (*domain.Order, error)) *OrderRepositoryMock_GetOrderByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrdersByUserID provides a mock function with given fields: ctx, userID
func (_m *OrderRepositoryMock) GetOrdersByUserID(ctx context.Context, userID int64) ([]*domain.Order, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrdersByUserID")
	}

	var r0 []*domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*domain.Order, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*domain.Order); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepositoryMock_GetOrdersByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrdersByUserID'
type OrderRepositoryMock_GetOrdersByUserID_Call struct {
	*mock.Call
}

// GetOrdersByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *OrderRepositoryMock_Expecter) GetOrdersByUserID(ctx interface{}, userID interface{}) *OrderRepositoryMock_GetOrdersByUserID_Call {
	return &OrderRepositoryMock_GetOrdersByUserID_Call{Call: _e.mock.On("GetOrdersByUserID", ctx, userID)}
}

func (_c *OrderRepositoryMock_GetOrdersByUserID_Call) Run(run func(ctx context.Context, userID int64)) *OrderRepositoryMock_GetOrdersByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *OrderRepositoryMock_GetOrdersByUserID_Call) Return(_a0 []*domain.Order, _a1 error) *OrderRepositoryMock_GetOrdersByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepositoryMock_GetOrdersByUserID_Call) RunAndReturn(run func(context.Context, int64) ([]*domain.Order, error)) *OrderRepositoryMock_GetOrdersByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingOrders provides a mock function with given fields: ctx
func (_m *OrderRepositoryMock) GetPendingOrders(ctx context.Context) ([]*domain.Order, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingOrders")
	}

	var r0 []*domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Order, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Order); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepositoryMock_GetPendingOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingOrders'
type OrderRepositoryMock_GetPendingOrders_Call struct {
	*mock.Call
}

// GetPendingOrders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *OrderRepositoryMock_Expecter) GetPendingOrders(ctx interface{}) *OrderRepositoryMock_GetPendingOrders_Call {
	return &OrderRepositoryMock_GetPendingOrders_Call{Call: _e.mock.On("GetPendingOrders", ctx)}
}

func (_c *OrderRepositoryMock_GetPendingOrders_Call) Run(run func(ctx context.Context)) *OrderRepositoryMock_GetPendingOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *OrderRepositoryMock_GetPendingOrders_Call) Return(_a0 []*domain.Order, _a1 error) *OrderRepositoryMock_GetPendingOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepositoryMock_GetPendingOrders_Call) RunAndReturn(run func(context.Context) ([]*domain.Order, error)) *OrderRepositoryMock_GetPendingOrders_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderStatus provides a mock function with given fields: ctx, number, status, accrual
func (_m *OrderRepositoryMock) UpdateOrderStatus(ctx context.Context, number string, status domain.OrderStatus, accrual *float64) error {
	ret := _m.Called(ctx, number, status, accrual)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.OrderStatus, *float64) error); ok {
		r0 = rf(ctx, number, status, accrual)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepositoryMock_UpdateOrderStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderStatus'
type OrderRepositoryMock_UpdateOrderStatus_Call struct {
	*mock.Call
}

// UpdateOrderStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - number string
//   - status domain.OrderStatus
//   - accrual *float64
func (_e *OrderRepositoryMock_Expecter) UpdateOrderStatus(ctx interface{}, number interface{}, status interface{}, accrual interface{}) *OrderRepositoryMock_UpdateOrderStatus_Call {
	return &OrderRepositoryMock_UpdateOrderStatus_Call{Call: _e.mock.On("UpdateOrderStatus", ctx, number, status, accrual)}
}

func (_c *OrderRepositoryMock_UpdateOrderStatus_Call) Run(run func(ctx context.Context, number string, status domain.OrderStatus, accrual *float64)) *OrderRepositoryMock_UpdateOrderStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.OrderStatus), args[3].(*float64))
	})
	return _c
}

func (_c *OrderRepositoryMock_UpdateOrderStatus_Call) Return(_a0 error) *OrderRepositoryMock_UpdateOrderStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepositoryMock_UpdateOrderStatus_Call) RunAndReturn(run func(context.Context, string, domain.OrderStatus, *float64) error) *OrderRepositoryMock_UpdateOrderStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderRepositoryMock creates a new instance of OrderRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepositoryMock {
	mock := &OrderRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
