// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/avc/loyalty-system-diploma/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// TransactionRepositoryMock is an autogenerated mock type for the TransactionRepository type
type TransactionRepositoryMock struct {
	mock.Mock
}

type TransactionRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionRepositoryMock) EXPECT() *TransactionRepositoryMock_Expecter {
	return &TransactionRepositoryMock_Expecter{mock: &_m.Mock}
}

// CreateTransaction provides a mock function with given fields: ctx, userID, orderNumber, amount, txType
func (_m *TransactionRepositoryMock) CreateTransaction(ctx context.Context, userID int64, orderNumber string, amount float64, txType domain.TransactionType) error {
	ret := _m.Called(ctx, userID, orderNumber, amount, txType)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, float64, domain.TransactionType) error); ok {
		r0 = rf(ctx, userID, orderNumber, amount, txType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionRepositoryMock_CreateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransaction'
type TransactionRepositoryMock_CreateTransaction_Call struct {
	*mock.Call
}

// CreateTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - orderNumber string
//   - amount float64
//   - txType domain.TransactionType
func (_e *TransactionRepositoryMock_Expecter) CreateTransaction(ctx interface{}, userID interface{}, orderNumber interface{}, amount interface{}, txType interface{}) *TransactionRepositoryMock_CreateTransaction_Call {
	return &TransactionRepositoryMock_CreateTransaction_Call{Call: _e.mock.On("CreateTransaction", ctx, userID, orderNumber, amount, txType)}
}

func (_c *TransactionRepositoryMock_CreateTransaction_Call) Run(run func(ctx context.Context, userID int64, orderNumber string, amount float64, txType domain.TransactionType)) *TransactionRepositoryMock_CreateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(float64), args[4].(domain.TransactionType))
	})
	return _c
}

func (_c *TransactionRepositoryMock_CreateTransaction_Call) Return(_a0 error) *TransactionRepositoryMock_CreateTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionRepositoryMock_CreateTransaction_Call) RunAndReturn(run func(context.Context, int64, string, float64, domain.TransactionType) error) *TransactionRepositoryMock_CreateTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function with given fields: ctx, userID
func (_m *TransactionRepositoryMock) GetBalance(ctx context.Context, userID int64) (*domain.Balance, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *domain.Balance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.Balance, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Balance); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Balance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionRepositoryMock_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type TransactionRepositoryMock_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *TransactionRepositoryMock_Expecter) GetBalance(ctx interface{}, userID interface{}) *TransactionRepositoryMock_GetBalance_Call {
	return &TransactionRepositoryMock_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, userID)}
}

func (_c *TransactionRepositoryMock_GetBalance_Call) Run(run func(ctx context.Context, userID int64)) *TransactionRepositoryMock_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *TransactionRepositoryMock_GetBalance_Call) Return(_a0 *domain.Balance, _a1 error) *TransactionRepositoryMock_GetBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionRepositoryMock_GetBalance_Call) RunAndReturn(run func(context.Context, int64) (*domain.Balance, error)) *TransactionRepositoryMock_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithdrawals provides a mock function with given fields: ctx, userID
func (_m *TransactionRepositoryMock) GetWithdrawals(ctx context.Context, userID int64) ([]*domain.Transaction, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawals")
	}

	var r0 []*domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*domain.Transaction, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*domain.Transaction); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionRepositoryMock_GetWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithdrawals'
type TransactionRepositoryMock_GetWithdrawals_Call struct {
	*mock.Call
}

// GetWithdrawals is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *TransactionRepositoryMock_Expecter) GetWithdrawals(ctx interface{}, userID interface{}) *TransactionRepositoryMock_GetWithdrawals_Call {
	return &TransactionRepositoryMock_GetWithdrawals_Call{Call: _e.mock.On("GetWithdrawals", ctx, userID)}
}

func (_c *TransactionRepositoryMock_GetWithdrawals_Call) Run(run func(ctx context.Context, userID int64)) *TransactionRepositoryMock_GetWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *TransactionRepositoryMock_GetWithdrawals_Call) Return(_a0 []*domain.Transaction, _a1 error) *TransactionRepositoryMock_GetWithdrawals_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionRepositoryMock_GetWithdrawals_Call) RunAndReturn(run func(context.Context, int64) ([]*domain.Transaction, error)) *TransactionRepositoryMock_GetWithdrawals_Call {
	_c.Call.Return(run)
	return _c
}

// WithdrawWithLock provides a mock function with given fields: ctx, userID, orderNumber, amount
func (_m *TransactionRepositoryMock) WithdrawWithLock(ctx context.Context, userID int64, orderNumber string, amount float64) error {
	ret := _m.Called(ctx, userID, orderNumber, amount)

	if len(ret) == 0 {
		panic("no return value specified for WithdrawWithLock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, float64) error); ok {
		r0 = rf(ctx, userID, orderNumber, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionRepositoryMock_WithdrawWithLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithdrawWithLock'
type TransactionRepositoryMock_WithdrawWithLock_Call struct {
	*mock.Call
}

// WithdrawWithLock is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - orderNumber string
//   - amount float64
func (_e *TransactionRepositoryMock_Expecter) WithdrawWithLock(ctx interface{}, userID interface{}, orderNumber interface{}, amount interface{}) *TransactionRepositoryMock_WithdrawWithLock_Call {
	return &TransactionRepositoryMock_WithdrawWithLock_Call{Call: _e.mock.On("WithdrawWithLock", ctx, userID, orderNumber, amount)}
}

func (_c *TransactionRepositoryMock_WithdrawWithLock_Call) Run(run func(ctx context.Context, userID int64, orderNumber string, amount float64)) *TransactionRepositoryMock_WithdrawWithLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(float64))
	})
	return _c
}

func (_c *TransactionRepositoryMock_WithdrawWithLock_Call) Return(_a0 error) *TransactionRepositoryMock_WithdrawWithLock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionRepositoryMock_WithdrawWithLock_Call) RunAndReturn(run func(context.Context, int64, string, float64) error) *TransactionRepositoryMock_WithdrawWithLock_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransactionRepositoryMock creates a new instance of TransactionRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepositoryMock {
	mock := &TransactionRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
