with-expecter: true
disable-version-string: true
mockname: "{{.InterfaceName}}Mock"
outpkg: mocks
dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceName | snakecase}}_mock.go"
structname: "{{.InterfaceName}}Mock"
packages:
  github.com/avc/loyalty-system-diploma/internal/domain:
    interfaces:
      UserRepository: {}
      OrderRepository: {}
      TransactionRepository: {}
      AuthService: {}
      OrderService: {}
      BalanceService: {}
      AccrualClient: {}
  github.com/avc/loyalty-system-diploma/internal/utils/password:
    interfaces:
      Hasher: {}
