// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HasherMock is an autogenerated mock type for the Hasher type
type HasherMock struct {
	mock.Mock
}

type HasherMock_Expecter struct {
	mock *mock.Mock
}

func (_m *HasherMock) EXPECT() *HasherMock_Expecter {
	return &HasherMock_Expecter{mock: &_m.Mock}
}

// Check provides a mock function with given fields: hash, _a1
func (_m *HasherMock) Check(hash string, _a1 string) error {
	ret := _m.Called(hash, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(hash, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HasherMock_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type HasherMock_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - hash string
//   - _a1 string
func (_e *HasherMock_Expecter) Check(hash interface{}, _a1 interface{}) *HasherMock_Check_Call {
	return &HasherMock_Check_Call{Call: _e.mock.On("Check", hash, _a1)}
}

func (_c *HasherMock_Check_Call) Run(run func(hash string, _a1 string)) *HasherMock_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *HasherMock_Check_Call) Return(_a0 error) *HasherMock_Check_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HasherMock_Check_Call) RunAndReturn(run func(string, string) error) *HasherMock_Check_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function with given fields: _a0
func (_m *HasherMock) Hash(_a0 string) (string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasherMock_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type HasherMock_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - _a0 string
func (_e *HasherMock_Expecter) Hash(_a0 interface{}) *HasherMock_Hash_Call {
	return &HasherMock_Hash_Call{Call: _e.mock.On("Hash", _a0)}
}

func (_c *HasherMock_Hash_Call) Run(run func(_a0 string)) *HasherMock_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *HasherMock_Hash_Call) Return(_a0 string, _a1 error) *HasherMock_Hash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HasherMock_Hash_Call) RunAndReturn(run func(string) (string, error)) *HasherMock_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// NewHasherMock creates a new instance of HasherMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHasherMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *HasherMock {
	mock := &HasherMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
